import type { Metadata } from 'next';
import './globals.css';
import { geistMono, geistSans, lato } from './styles/Fonts';

export const metadata: Metadata = {
	title: 'Simplicity',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
